name: Update Xray Server
on:
  push:
    branches:
      - 'server'
jobs:
  job:
    name: Update Xray Config
    runs-on: ubuntu-20.04
    steps:
      - name: checkoutå‡ºxray-parseré¡¹ç›®
        uses: actions/checkout@v3.5.2
        with:
          repository: nichuanfang/xray-parser
          path: xray-parser
          ref: server
          token: ${{ secrets.GH_TOKEN }}

      - name: checkoutå‡ºdockeré¡¹ç›®
        uses: actions/checkout@v3.5.2
        with:
          repository: nichuanfang/docker
          path: docker
          ref: master
          token: ${{ secrets.GH_TOKEN }}

      - name: xray-parser=>docker
        run: cp -r $GITHUB_WORKSPACE/xray-parser $GITHUB_WORKSPACE/docker/dockerfile_work/xray

      - name: å¯¼å…¥pipä¾èµ–
        run: pip install -i https://pypi.tuna.tsinghua.edu.cn/simple -r $GITHUB_WORKSPACE/docker/dockerfile_work/xray/xray-parser/requirements.txt

      - name: é…ç½®xrayç¯å¢ƒ ç”¨æ¥ç”ŸæˆæœåŠ¡ç«¯å’Œå®¢æˆ·ç«¯é€šç”¨æ•°æ®
        run: |
          sudo apt-get install wget unzip -y
          wget https://github.com/XTLS/Xray-core/releases/download/v1.8.1/Xray-linux-64.zip
          unzip Xray-linux-64.zip
          chmod +x ./xray
          cp ./xray $GITHUB_WORKSPACE/docker/dockerfile_work/xray/xray-parser

      - name: æ›´æ–°config.jsonå’Œdocker-compose.yml
        run: |
          cd $GITHUB_WORKSPACE/docker/dockerfile_work/xray/xray-parser
          python build.py ${{vars.VLESS_DEST}} ${{vars.VLESS_SERVER_NAMES}} ${{vars.VLESS_PORT}} ${{vars.TROJAN_PORT}}

      - name: æäº¤ä¹‹å‰çš„å‡†å¤‡å·¥ä½œ
        run: |
          mkdir -p $GITHUB_WORKSPACE/docker/dockerfile_work/xray/config
          cat $GITHUB_WORKSPACE/docker/dockerfile_work/xray/xray-parser/dist/config.json
          cp -rf $GITHUB_WORKSPACE/docker/dockerfile_work/xray/xray-parser/dist/config.json $GITHUB_WORKSPACE/docker/dockerfile_work/xray/config

      # åˆ é™¤dockeré¡¹ç›®çš„xray-parserç›®å½•
      - name: åˆ é™¤dockeré¡¹ç›®çš„xray-parserç›®å½•
        run: rm -rf $GITHUB_WORKSPACE/docker/dockerfile_work/xray/xray-parser

      # è§¦å‘å·¥ä½œæµ
      - name: æ›´æ–°dockeré¡¹ç›®çš„config.jsonå’Œdocker-compose.yml
        uses: Smart-Transportation/push@v1.3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          branch: 'master'
          author_email: 'github-actions[bot]@users.noreply.github.com'
          author_name: 'github-actions[bot]'
          message: 'ğŸ³ chore: æ›´æ–°xrayæœåŠ¡ç«¯é…ç½®æ–‡ä»¶'
          directory: /home/runner/work/xray-parser/xray-parser/docker
          repository: nichuanfang/docker

      - name: åˆå§‹åŒ–xrayå®¢æˆ·ç«¯
        uses: rshop/trigger-workflow-action@v1
        with:
          token: ${{ secrets.GH_TOKEN }}
          repository: 'nichuanfang/xray-parser'
          workflowId: 57684788
          branch: client
